version: '3.8'
    
services:
  front_map:
    container_name: front_map
    build: ./Frontend/AftertimeMAP
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.11
      default:
    ports:
      - 3000:3000
  demo:
    container_name: demo_django
    build: ./Demo/react-demo
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.10
  app:
    container_name: core
    build: ./Backend/AftertimeBalance_backend
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.20
      default:
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
  db:
    container_name: db-general
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: aftertime
      POSTGRES_PASSWORD: aftertime
      POSTGRES_DB: aftertime
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    networks:
      back:
        ipv4_address: 172.16.238.200
      default:
    ports:
      - 5532:5432
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      back:
        ipv4_address: 172.16.238.4
      default:
    volumes:
      - ./nginx_manager/data:/data
      - ./nginx_manager/letsencrypt:/etc/letsencrypt

networks:
  back:
    driver: bridge
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
  default:
    driver: bridge
