version: '3.8'
    
services:
  db:
    container_name: db-general
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: aftertime
      POSTGRES_PASSWORD: aftertime
      POSTGRES_DB: aftertime
    volumes:
      - ./core/infrastructure/postgress/pgdata:/var/lib/postgresql/data
    networks:
      back:
        ipv4_address: 172.16.238.200
      default:
    ports:
      - 5532:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U aftertime -d aftertime'"]
      interval: 10s
      timeout: 3s
      retries: 3
  front_balance:
    container_name: front_balance
    build:
      context: ./core/frontend/aftertime_balance_front
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_SERVER_FRONT=$REACT_APP_API_SERVER_FRONT
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.12
      default:
    # ports:
    #   - 3000:3000        
  front_map:
    container_name: front_map
    build:
      context: ./core/frontend/aftertime_vessile_front
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_SERVER_FRONT=$REACT_APP_API_SERVER_FRONT
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.11
      default:
    # ports:
    #  - 3001:3000
  app:
    container_name: core
    build: 
      context: ./core/backend/aftertime_core_back
      dockerfile: Dockerfile
    restart: always
    networks:
      back:
        ipv4_address: 172.16.238.20
      default:
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      back:
        ipv4_address: 172.16.238.4
      default:
    volumes:
      - ./core/infrastructure/nginx_manager/data:/data
      - ./core/infrastructure/nginx_manager/letsencrypt:/etc/letsencrypt

networks:
  back:
    driver: bridge
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
  default:
    driver: bridge
